mode: rgb

lm:
  automatic_optimization: true
  model:
    cls_name: FLIPMCL
    input_size: [224, 224]
    ssl_mlp_dim: 256
    ssl_emb_dim: 256
    modality: rgb

  solver:
    optimizer:
      cls_name: AdamW
      lr: 1.e-6
      weight_decay: 1.e-6
    lr_scheduler:
      cls_name: OneCycleLR
      max_lr: 1.e-6
      pct_start: 0.1
      anneal_strategy: cos
      final_div_factor: 1
      div_factor: 10

trainer:
  precision: bf16-mixed
  max_epochs: 20
  accelerator: gpu
  benchmark: false
  deterministic: true
  num_sanity_val_steps: 0
